# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: hasanprojects
# "service" is the name of this project. This will also be added to your AWS resource names.
service: Shui-backend

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-north-1
  stage: dev
  iam:
    role: arn:aws:iam::361920973367:role/Fe_24_Hasan
  httpApi:
    cors:
      allowedOrigins:
        - http://localhost:5173
        - http://shui-frontend-dev-hasan.s3-website-eu-north-1.amazonaws.com
      allowedMethods: [GET, POST, PUT, OPTIONS]
      allowedHeaders: [Content-Type]
  environment:
    TABLE_NAME: shui_messages

functions:
  createMessage:
    handler: functions/createMessage/index.handler
    events:
      - httpApi:
          path: /messages
          method: post

  updateMessage:
    handler: functions/updateMessage/index.handler
    events:
      - httpApi:
          path: /messages/{id}
          method: put

  listMessages:
    handler: functions/listMessages/index.handler
    events:
      - httpApi:
          path: /messages
          method: get

resources:
  Resources:
    MessagesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: shui_messages 
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: PK
            AttributeType: S
          - AttributeName: SK
            AttributeType: S
          - AttributeName: TYPE
            AttributeType: S
          - AttributeName: USER
            AttributeType: S
          - AttributeName: createdAt
            AttributeType: S
        KeySchema:
          - AttributeName: PK
            KeyType: HASH
          - AttributeName: SK
            KeyType: RANGE
        GlobalSecondaryIndexes:
          - IndexName: GSI_All_ByDate
            KeySchema:
              - AttributeName: TYPE
                KeyType: HASH
              - AttributeName: createdAt
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
          - IndexName: GSI_ByUser_ByDate
            KeySchema:
              - AttributeName: USER
                KeyType: HASH
              - AttributeName: createdAt
                KeyType: RANGE
            Projection:
              ProjectionType: ALL

    FrontendBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: shui-frontend-dev-hasan 
        WebsiteConfiguration:
          IndexDocument: index.html
          ErrorDocument: index.html
        PublicAccessBlockConfiguration:
          BlockPublicAcls: true
          BlockPublicPolicy: false
          IgnorePublicAcls: true
          RestrictPublicBuckets: false

    FrontendBucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket: !Ref FrontendBucket
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Sid: PublicReadForWebsite
              Effect: Allow
              Principal: '*'
              Action: s3:GetObject
              Resource: arn:aws:s3:::shui-frontend-dev-hasan/*

  Outputs:
    ApiBaseUrl:
      Value:
        Fn::Sub: https://${HttpApi}.execute-api.${AWS::Region}.amazonaws.com
    WebsiteURL:
      Value: !GetAtt FrontendBucket.WebsiteURL

